### ISSUE TITLE
Feature request: adding Hitevents 

### ISSUE THREAD

**Issue by shigetiro** [tosuapp/tosu#151]
I found that there was something called heatmap for Gosumemory but since the inactivity from both the fork owner and the Gosu owner it doesn't got into the master branch the guy who made it created years ago a Pull Request here: https://github.com/l3lackShark/gosumemory/pull/145 maybe you can implement it into tosu it would be a need Feature for Replay overlays and livestreaming so that the viewers can see exactly how he missed gonna put a pic into the request to show how it would be look like 
![preview_std_heatmap](https://github.com/KotRikD/tosu/assets/24944943/1e74b9a1-b131-43e8-be58-fbbc6d37475f)

**Comment by KotRikD** [comment]
As other solution, we can take uzervlad pr to rosu-memory https://github.com/486c/rosu-memory/pull/29

I will check as soon, as I will have some free time

**Comment by KotRikD** [comment]
Temporary will put help wanted tag

**Comment by KotRikD** [comment]
More details: hitEvents can potentially be used in bad ways of game. For security reasons we will not be doing that....
