### ISSUE TITLE
fault `resultsScreen.rank` value in CTB mode

### ISSUE THREAD

**Issue by mas-alone** [tosuapp/tosu#206]
example osr here:
[osr.zip](https://github.com/user-attachments/files/17389160/osr.zip)

in the `C rank.osk`, the true rank is C, but in `resultsScreen.rank` value is X (S)

in the `B rank.osk`, the true rank is B, but in `resultsScreen.rank` value is A

The effect of `Katu` (Drp Miss) on the ctb mode seems does not appear to have been calculated
![B](https://github.com/user-attachments/assets/2769d603-ff5c-42ff-a64f-b6123bf083fe)
![C](https://github.com/user-attachments/assets/ee8eaeda-4763-4ff0-9597-6c26a7497d76)

**Comment by cyperdark** [comment]
Test this build: https://github.com/tosuapp/tosu/actions/runs/11364089631/job/31609395151

**Comment by mas-alone** [comment]
> Test this build: https://github.com/tosuapp/tosu/actions/runs/11364089631/job/31609395151

Super speed. ty cy! it fixed
![QQ20241016-191942](https://github.com/user-attachments/assets/b313cfcd-e4c1-47f7-9b4b-bedfd97abc9a)

**Comment by cyperdark** [comment]
👍
