### ISSUE TITLE
relax pp off

### ISSUE THREAD

**Issue by EverybodyDanceNow** [tosuapp/tosu#211]
heya. first i'd like to say amazing memory reader. does all i've ever wanted it to.

one question

would it be possible (or is it possible?) to somehow turn off relax check for pp counters? it is just for an experiment of mine wherein i'd like to be able to see vanilla pp while playing relax without having it be severely depleted by the relax mod check. a hypothetical of sorts to how far i could push my abilities if I COULD tap without a missed beat.

**Comment by cyperdark** [comment]
we have an api route to calculate pp for your needs
![image](https://github.com/user-attachments/assets/ef939123-0ca6-4e06-b4e5-a6a359fbff50)

https://github.com/tosuapp/tosu?tab=readme-ov-file#routes


example of how you can request pp via this route: https://github.com/tosuapp/counters/blob/master/quickstart/js/socket.js#L104
