### ISSUE TITLE
how do i fix this bug

### ISSUE THREAD

**Issue by sw97awesome** [tosuapp/tosu#215]
It opens fine and I can download the counters fine, but I keep getting an error that says "Pattern scanning failed, trying one more time"
![image](https://github.com/user-attachments/assets/cc8abc32-c85d-4d8a-9126-e27ceec48ef0)
How do I fix this

**Comment by cyperdark** [comment]
# How to report issue

1. Describe your issue as detailed as possible
2. Where does **tosu.exe** located (Folder path, Example: D:\tosu\tosu.exe)
3. Record video showing:
   - tosu.env & config.ini
   - Enable debug in settings
   - Close tosu, then start it again
   - Open osu and show what not working
4. Windows or Linux
