### ISSUE TITLE
KeyOverlay missing quick and brief presses

### ISSUE THREAD

**Issue by Doubi-wert** [tosuapp/tosu#216]
The keyoverlay often misses several key presses, especially when the keys are pressed briefly. And I've tried every modules that has keyoverlay, it happens from time to time.
The keyboard I'm using is a magnetic switch keyboard with rapid trigger function.

one of my gameplay videos shows this:    https://www.bilibili.com/video/BV1jXsyekE82   (my other match replays also has similar situation)
I am an alternate player, so when 'D' is pressed, the next key i pressed must be 'F'. And the bug happens at 00:04:28 , 00:04:31 , 00:04:33 , 00:04:37(this time none of my presses are shown in form of bars) and etc.(very frequently when i press the key too briefly)

D:\tosu\tosu.exe
Windows

**Comment by cyperdark** [comment]
set PRECISE_DATA_POLL_RATE to 0
http://127.0.0.1:24050/?tab=2
