### ISSUE TITLE
Bug report: The settings pop-up doesn't hide when hiding the in-game overlay editor

### ISSUE THREAD

**Issue by KapiWilq** [tosuapp/tosu#224]
When manually editing an overlay in the new in-game overlay editor, when you hide the editor, the settings pop-up stays on the screen, and you can't interact with it until you enable the overlay editor again.

https://github.com/user-attachments/assets/79f389e7-666f-404c-9408-b40f4bc72e47

**Comment by cyperdark** [comment]
@KapiWilq try this build https://github.com/tosuapp/tosu/actions/runs/11839336399

**Comment by KapiWilq** [comment]
> @KapiWilq try this build https://github.com/tosuapp/tosu/actions/runs/11839336399

This fixes the issue for me, thanks

**Comment by KapiWilq** [comment]
@cyperdark Update: just discovered the same is happening to the other settings pop-up as well:
![image](https://github.com/user-attachments/assets/6b7cbb68-515e-42c5-bd7b-e05ba5e790d1)
