### ISSUE TITLE
Latest Release is flagged as Virus by Windows Security

### ISSUE THREAD

**Issue by NotJansel** [tosuapp/tosu#225]
When updating the latest version, it gets flagged as virus, no matter if u update through github releases or web UI.
![{934E3C51-13CC-432A-92D0-A64405F0342D}](https://github.com/user-attachments/assets/958ecc79-adfe-4656-bcaf-4e87c66a269f)

**Comment by KotRikD** [comment]
Wacatac is mostly triggers on any self-executables like archives unfortunately( 

As I said before: i don't have opportunity to make myself digital sign for applications. You can thank world shit for that
More details you can check by watching peppy video https://youtu.be/Kqu4TUOO5IY?si=akodBReLridtTa1s&t=517

I will send to microsoft lab for analyzing, should be okay after that

**Comment by NotJansel** [comment]
update: it doesnt flag anymore, just screams the smartscreen window as always on first run now

**Comment by KotRikD** [comment]
> update: it doesnt flag anymore, just screams the smartscreen window as always on first run now

![изображение](https://github.com/user-attachments/assets/7d9fff92-44e3-4b05-a70b-ccb728823f1d)
