### ISSUE TITLE
fix: Float-pointing numbers not fitting into the text box.

### ISSUE THREAD

**Issue by GabuTheDev** [tosuapp/tosu#226]
Reproducible if overlay resize is done manually by holding ctrl.

![image](https://github.com/user-attachments/assets/49aaa64c-68e9-4d46-ad67-278b212e071c)

**Comment by cyperdark** [comment]
@GabuTheDev try this build https://github.com/tosuapp/tosu/actions/runs/11839336399

**Comment by GabuTheDev** [comment]
> @GabuTheDev try this build https://github.com/tosuapp/tosu/actions/runs/11839336399

Still present 
![image](https://github.com/user-attachments/assets/3f720d56-4311-48e0-8b97-48e44652160b)
