### ISSUE TITLE
Windows Defender virus detection

### ISSUE THREAD

**Issue by yashi391** [tosuapp/tosu#229]
When downloading tosu 4.0.0 I got a thread detection from windows defender.
I'm using Windows 10 on the latest version. The .exe was downloaded directly from the rep.
![image](https://github.com/user-attachments/assets/b2121f6e-d160-415b-aa85-4246802983cc)
![image](https://github.com/user-attachments/assets/40e66266-e7e9-4270-bed4-d4b570da4bcc)

**Comment by cyperdark** [comment]
https://github.com/tosuapp/tosu/issues/225#issuecomment-2473011263

**Comment by KotRikD** [comment]
![изображение](https://github.com/user-attachments/assets/d9c8d27a-852e-4b59-ad07-e595a2d2b326)
