### ISSUE TITLE
tosu stops working with stable after running with lazer

### ISSUE THREAD

**Issue by EWReinE** [tosuapp/tosu#236]
So I normally stream osu on stable client but today I got a new overlay and needed to adjust a bunch of things. so I initially opened up obs, tosu and osu stable to work on that and later decided to setup a lazer overlay . so i closed osu stable and opened lazer. I set that up and when I tried to run it again in stable, it wouldn't work anymore. I unfortunately cannot replicate this event. However, everytime I now run tosu with stable I get the same result (even after I delete the folder and redownloadc or restart pc).

Below are logs of me trying to figure out what happened. A lot of them are me just having tosu open but I'd recommend checking files 1731729871971, 1731730294009, and 1731730933973 as those are the ones that show the repeating error. For some reason I am unable to find the log for the previous few hours of tosu running fine on stable but I will keep looking and attach it if I find it. 

[1731729853598.txt](https://github.com/user-attachments/files/17783514/1731729853598.txt)
[1731729871971.txt](https://github.com/user-attachments/files/17783515/1731729871971.txt)
[1731730269073.txt](https://github.com/user-attachments/files/17783516/1731730269073.txt)
[1731730294009.txt](https://github.com/user-attachments/files/17783517/1731730294009.txt)
[1731730834118.txt](https://github.com/user-attachments/files/17783518/1731730834118.txt)
[1731730905845.txt](https://github.com/user-attachments/files/17783519/1731730905845.txt)
[1731730933973.txt](https://github.com/user-attachments/files/17783520/1731730933973.txt)
[1731731738759.txt](https://github.com/user-attachments/files/17783521/1731731738759.txt)
[1731731738971.txt](https://github.com/user-attachments/files/17783522/1731731738971.txt)

tosu folder filepath  =  C:\Users\ericw\AppData\Local\tosu

the video file is too big so i've attached a google drive link for the video. if the link doesn't work, you can copy/paste link in browser and it should work.
[https://drive.google.com/file/d/1Fr5gFRnFk47wkUzEySUbiBgF-jjuxP9u/view?usp=drive_link](url)

I didn't see a config file after deleting the original version but I restored the old config file after I recorded the video. I don't know if it makes a difference though because I was getting the same result with and without the config file. 

![image](https://github.com/user-attachments/assets/f1dd999d-cf6c-49a5-9aff-43e4ffc2273c)
![image](https://github.com/user-attachments/assets/bafd0c3e-2299-4938-bb6d-1c22c5a0899b)

I am running windows 11.

**Comment by cyperdark** [comment]
google drive link is broken

**Comment by EWReinE** [comment]
try now. [https://drive.google.com/file/d/1Fr5gFRnFk47wkUzEySUbiBgF-jjuxP9u/view?usp=sharing](url)
also I've managed to fix my issue by downloading gosumemory.

**Comment by cyperdark** [comment]
@EWReinE try changing default skin to something else

**Comment by EWReinE** [comment]
@cyperdark I've already fixed the issue on my side. What I'm trying to do now is figure out how to replicate the problem so I understand what I did to cause it and why it happened so it doesn't happen to anyone else.

**Comment by EWReinE** [comment]
I'll close this for now since I can't replicate the problem but if I figure out how to replicate the problem I'll reopen this.

**Comment by cyperdark** [comment]
i can replicate this very easily, i'll open another issue, so kotrik or cherry can fix it later on

https://github.com/user-attachments/assets/75e3eeff-dd4b-4b56-80ea-2b48512b2ec3

**Comment by EWReinE** [comment]
Ok
