### ISSUE TITLE
in-game overlay doesn't work when the osu's compatibility mode is on

### ISSUE THREAD

**Issue by LeoBlackMT** [tosuapp/tosu#237]
# Description
The tosu v4.0.1 in-game overlay doesn't work when the osu's compatibility mode is on. I can't switch off the button " Compatibility mode" and under of the button the game say "Compatibilty mode has been forced for better compatibility with NVIDIA Optimus systems." 
I found the tosu_overlay.exe was successfully launched in the taskmgr , but when I switch to my game and start a play , it did't display anything , even I pressed Ctrl+Shift+Space.
After a few try I successfully disabled compatibility mode, and the in-game overlay ran correctly.

# Path
C:\Games\osu!\tosu\tosu.exe
C:\Games\osu!\tosu\game-overlay\x86\tosu_overlay.exe (which i found in taskmgr)
C:\Games\osu!\osu!.exe

# Environment
Windows 11 23H2 x64
i9-13980HX with 4060laptop
tosu version 4.0.1
osu version b20241030

# Config & log

## Debug log
[1731736552782.txt](https://github.com/user-attachments/files/17783728/1731736552782.txt)

## tsosu.env
DEBUG_LOG=true
CALCULATE_PP=true
ENABLE_AUTOUPDATE=true
OPEN_DASHBOARD_ON_STARTUP=false
ENABLE_INGAME_OVERLAY=true
ENABLE_KEY_OVERLAY=true
ALLOWED_IPS=127.0.0.1,localhost
POLL_RATE=100
PRECISE_DATA_POLL_RATE=100
SHOW_MP_COMMANDS=false
SERVER_IP=127.0.0.1
SERVER_PORT=24050
STATIC_FOLDER_PATH=./static

## osu settings
Compatibility mode & Fullscreen
others are default

**Comment by GabuTheDev** [comment]
What compatibility mode on osu!stable does is to enable a translation layer from OpenGL to DirectX graphics API. Tosu's in-game overlay runs exclusively on the openGL API due to chrome's framework.

I'm not sure if this will be possible, but you better wait for @KotRikD to answer.

**Comment by KotRikD** [comment]
> What compatibility mode on osu!stable does is to enable a translation layer from OpenGL to DirectX graphics API. Tosu's in-game overlay runs exclusively on the openGL API due to chrome's framework.
> 
> I'm not sure if this will be possible, but you better wait for @KotRikD to answer.

It's not because of chrome's framework, it gives array of pixels, so it can be implemented in any graphics. It's just us, we made only OpenGL support for now, because it's much easier to understand API than DirectX one

**Comment by KotRikD** [comment]
I will close issue for now, will be implemented later
