### ISSUE TITLE
Different logging type on cmd, compared to the log file.

### ISSUE THREAD

**Issue by GabuTheDev** [tosuapp/tosu#252]
In cmd it's **WARN**, but in log file is **ERROR**
another thing is that in the logs, there's no tosu version mentioned.

![image](https://github.com/user-attachments/assets/59fa7515-1d0f-4ee9-b2b7-d122f6b021c7)

and sometimes, **message order** in the log file also wrong. (see timestamps)
![image](https://github.com/user-attachments/assets/4b235389-fd18-4702-bad8-d08d290eb51c)

**Comment by cyperdark** [comment]
> and sometimes, message order in the log file also wrong. (see timestamps)

it prints message first, and then write to log file
![image](https://github.com/user-attachments/assets/d384905a-c211-437e-9ec7-b123cd7efbb7)

![image](https://github.com/user-attachments/assets/cf21e927-169a-453e-8292-29211c6812de)
