### ISSUE TITLE
lazer: updateLeaderboard | Couldn't read long at 18 / 1a4548e8 / 1a4546d1

### ISSUE THREAD

**Issue by unqxl** [tosuapp/tosu#267]
First of all, this problem has no specific way of reproducing, it just appeared by itself out of nowhere (and as seen earlier, I'm not the only one).

Below I will attach a link to a video with a clear example of how I managed to reproduce the error, and I showed different examples:
1. In the first case, I ran the Loved map with AutoPlay, and as you can see the was no `updateLeaderboard` error, but was another one, I will point it out below.
2. In the second case, I played the same map without AP, and as you can see, there was a bug and spam in the console.
3. Ranked and local maps also did not gave any other results, except that the local map instead of a set of letters and numbers was the number 18

tosu path is `E:\Software\tosu`, so i don't think that there's problem with that.

Errors, that I also encountered (while AP):
1. `lazer 2700 gameplay updateHitErrors Couldn't read int at 1000218`
2. `lazer 2700 gameplay updateHitErrors Couldn't read long at 1bf7ac6`

OS is Windows.
Video link: https://youtu.be/RxG1KA4fko4

**Comment by cyperdark** [comment]
@KotRikD @xxCherry

**Comment by KotRikD** [comment]
@unqxl Is problem consist after 4.1.4 update?

**Comment by unqxl** [comment]
looks like that error is gone, no other errors were encountered
