### ISSUE TITLE
Unable to read pp of some third-party lazer rulesets

### ISSUE THREAD

**Issue by WhatDamon** [tosuapp/tosu#268]
## Describe your issue as detailed as possible

Some third-party rulesets in lazer don't get the current pp correctly
The command line shows messages like...

- `initModMapping Unknown mods gamemode: -1` _(WARNING)_
- `gameplay updateStarsAndPerformance memory access out of bounds` _(ERROR)_
- `gameplay updateStarsAndPerformance recursive use of an object detected which would lead to unsafe aliasing in rust` _(ERROR)_

0 pp on the output counter

## Where does **tosu.exe** located (Folder path, Example: D:\tosu\tosu.exe)

`D:\Desktop\tosu-windows-v4.1.3\tosu.exe`

## Record video showing:
   
None

## Windows or Linux

Windows 11 24H2

**Comment by KotRikD** [comment]
...

**Comment by GabuTheDev** [comment]
To give out a proper answer, the tosu team covered all official rulesets present in both clients (stable and lazer).
Tosu will not support any third-party rulesets in the near future for many reasons.

If you want tosu to support this, feel free to implement it yourself by forking the repo.

**Comment by KotRikD** [comment]
Thanks Gabu, for translating my bad words)

**Comment by DGCK81LNN** [comment]
Well it would be nice if tosu didn't just crash on custom ruleset results screen. I only need the song info.

~~~
4.19.1  ┃  00:03:46.938  Unknown lazer game mode: -1
4.19.1  ┃  00:03:47.040  Unknown lazer game mode: -1
4.19.1  ┃  00:03:47.142  Unknown lazer game mode: -1
4.19.1  ┃  00:03:47.244  Unknown lazer game mode: -1
4.19.1  ┃  00:03:47.346  Unknown lazer game mode: -1
4.19.1  ┃  00:03:47.447  Unknown lazer game mode: -1
4.19.1  ┃  00:03:47.550  Unknown lazer game mode: -1
4.19.1  ┃  00:03:47.652  Unknown lazer game mode: -1
4.19.1  ┃  00:03:47.754  Unknown lazer game mode: -1
4.19.1  ┃  00:03:47.856  Unknown lazer game mode: -1
4.19.1  ┃  00:03:47.957  Unknown lazer game mode: -1
4.19.1  ┃  00:03:48.058  Unknown lazer game mode: -1
wasm://wasm/002dd0f6:1


RuntimeError: memory access out of bounds
    at wasm://wasm/002dd0f6:wasm-function[543]:0x9ffba
    at C:\snapshot\dist\index.js
    at FinalizationRegistry.cleanupSome (<anonymous>)

Node.js v20.19.6
~~~

I know it'd take extra effort to fix but I really need it.

Is it possible to just give up reading gameplay related data when an unknown gamemode is detected?

**Comment by cyperdark** [comment]
probably possible, but I can't do that because I don't want to do anything debugging related in tosu

@KotRikD @GabuTheDev

**Comment by GabuTheDev** [comment]
I'm personally not interested in supporting other non-official rulesets.
I'd much rather have their specific developers PR because they know the best about their own ruleset.

Regarding the crash, tosu shouldn't do that if it can't read stuff out. That's on us.
We should implement a safe readout that just cancel the flow, instead of crashing the whole app.
All rulesets depend on the beatmap structure the official rulesets have, so having tosu crash on data that's always available makes no sense.

It would be worth opening a new issue regarding this. This specific issue is not related.
@DGCK81LNN @cyperdark
