### ISSUE TITLE
Broken after lazer update.

### ISSUE THREAD

**Issue by 0120-500-500** [tosuapp/tosu#270]
1. Describe your issue as detailed as possible
After today's lazer update, tosu recognizes the client but does not read it correctly during play!
2. Where does **tosu.exe** located (Folder path, Example: D:\tosu\tosu.exe)
"E:\tosu\tosu.exe"
3. Record video showing:
   - tosu.env & config.ini
   - Enable debug in settings
   - Close tosu, then start it again
   - Open osu and show what not working
4. Windows or Linux
Win11

https://github.com/user-attachments/assets/4cb9fd04-16c2-4002-8f00-380e76285610

**Comment by GabuTheDev** [comment]
After the recent Lazer update, the game has changed it's memory offsets and tosu can't read data anymore.
Please wait for an update.

**Comment by KotRikD** [comment]
Should be fixed in 4.1.4
